---
title: "Google Play Store Data Analysis"
author: "Anthony Le"
date: "September 28, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,echo=FALSE}
#install.packages("tidyverse")
#install.packages("ggplot2")
#library(ggplot2)
library(tidyverse)
library(lubridate)
```

## Cleaning Data

Import Data 
```{r}
playstore <- read.csv('googleplaystore.csv', header = TRUE)
```


Initial Data
```{r,echo=FALSE}
str(playstore)
summary(playstore)

```

Remove nonessential columns and duplicated rows

```{r}
playstore$App <- NULL
playstore$Current.Ver <- NULL
playstore$Genres <- NULL
playstore$Last.Updated <- NULL
playstore <- na.omit(playstore)
playstore <- subset(unique(playstore))

```
App ratings should have a maximum value of 5

```{r, echo=FALSE}
playstore <- subset(playstore[playstore$Rating <= 5,])
summary(playstore)
#str(playstore)
#boxplot(playstore$Rating, main = "Distribution of Rating", xlab = "App Rating", col="red")
```


Remove extra characters, convert Size to consistent format, remove apps with 0 installs

```{r,echo=FALSE}
playstore$Installs <- gsub("+", "", playstore$Installs, fixed = TRUE)
playstore$Installs <- gsub(",", "", playstore$Installs, fixed = TRUE)
playstore$Price <- gsub("$", "", playstore$Price, fixed = TRUE)
playstore <- subset(playstore[playstore$Size != "Varies with device",])
playstore$Size <- gsub("M", "", playstore$Size)
playstore$Size <- as.numeric(playstore$Size)
playstore[,4][is.na(playstore$Size)] <- 0

```



Convert columns to appropriate variable types

```{r, echo=FALSE}

# Android.Ver should have numeric values only
playstore$Android.Ver <- gsub("and up","",playstore$Android.Ver,fixed=TRUE)
playstore$Android.Ver <- gsub("Varies with device",NA,playstore$Android.Ver)
playstore <- na.omit(playstore)
playstore$Android.Ver <- substr(playstore$Android.Ver,start=1,stop=3)

# Change data type of  Reviews, Rating, Price, Installs
playstore$Reviews <- as.numeric(playstore$Reviews)
playstore$Rating <- as.numeric(playstore$Rating)
playstore$Price <- as.numeric(playstore$Price)
playstore$Installs <- as.numeric(playstore$Installs)

# Remove NaN values in Type
playstore$Type <- gsub(NaN,NA,playstore$Type,fixed=TRUE)
playstore$Android.Ver <- gsub(NaN,NA,playstore$Android.Ver,fixed=TRUE)
playstore$Android.Ver <- as.factor(playstore$Android.Ver)

playstore <- na.omit(playstore)

str(playstore)

```

##Exploratory Plots

```{r,echo=FALSE}
hist(playstore$Rating, main = "Distribution of App Rating", breaks = 100, xlim = c(0,5), xlab = "Rating", ylab = "Count", col="blue")

```
